version: 2
updates:
  # Monitor Gradle dependencies (build.gradle / build.gradle.kts)
  - package-ecosystem: "gradle"
    directory: "/"   # Location of your build.gradle
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

  # Monitor GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"